// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrototipoERP.Infraestrutura.Database;

namespace PrototipoERP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211212150454_CriarModelosDatabasePrototipo")]
    partial class CriarModelosDatabasePrototipo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("PrototipoERP.Entidades.Lembrete", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("DATETIME");

                    b.Property<string>("TextoLembrete")
                        .IsRequired()
                        .HasColumnType("VARCHAR(250)");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("lembretes");
                });

            modelBuilder.Entity("PrototipoERP.Entidades.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("PrototipoERP.Entidades.Lembrete", b =>
                {
                    b.HasOne("PrototipoERP.Entidades.Usuario", "Usuario")
                        .WithMany("Lembretes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PrototipoERP.Entidades.Usuario", b =>
                {
                    b.Navigation("Lembretes");
                });
#pragma warning restore 612, 618
        }
    }
}
